### ISSUE TITLE
Says "You do not have a driivers license" even though I do have one.

### ISSUE THREAD

**Issue by DuckyOnThatQuack** [AnishBplayz/ab-rentals#1]
I cannot rent a car since the script thinks I do not have a drivers license even though I do. No errors anywhere.

**Comment by AnishBplayz** [comment]
Have you tried license = false in config ? and are you trying the car rentals or boat rentals ?

**Comment by DuckyOnThatQuack** [comment]
This is for car rentals. I only want players with a license to be able to rent cars.

**Comment by AnishBplayz** [comment]
I just tested it on a fresh qbcore server and it seems the issue doesn't persist for me check your core and try printing your metadata if driver license it true
